version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/glean"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/samples/browser/webext/typescript"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/samples/browser/webext/javascript"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/samples/browser/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/samples/node"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/glean/tests/unit/platform/utils/webext/sample"
    schedule:
      interval: "weekly"
