version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/glean"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/samples/web-extension/typescript"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/samples/web-extension/javascript"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/glean/tests/unit/platform/utils/webext/sample"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/samples/qt-qml-app"
    schedule:
      interval: "daily"
